# =============================================================================
# CodeLadder Production Docker Compose Configuration
# 
# This file defines the production environment services:
# - Backend: Node.js/Express API server (optimized build)
# - Frontend: Nginx serving static files (optimized build)
# 
# Features:
# - Production-optimized builds
# - Health checks for container orchestration
# - Automatic service restart
# - Shared network for service communication
# =============================================================================

version: '3.8'

services:
  # ============================= BACKEND SERVICE ==============================
  backend:
    build:
      # Build context is the project root directory
      context: ../../
      # Use production Dockerfile for backend, path relative to context
      dockerfile: infra/docker/backend/Dockerfile.backend
    env_file:
      # Reference root .env file, path relative to this docker-compose.yml file
      - ../../.env  
    environment:
      # Force production mode
      - NODE_ENV=production
    ports:
      # Expose API port
      - "8000:8000"
    healthcheck:
      # Regular health checks for container orchestration
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      # Connect to shared network for inter-service communication
      - app-network
    # Automatically restart on failure
    restart: always

  # ============================= FRONTEND SERVICE ============================
  frontend:
    build:
      # Context: Relative to this docker-compose.yml file.
      # If this file is in infra/docker/ and frontend source is in the project's frontend/ dir,
      # context is ../../frontend (i.e. /home/ec2-user/codeladder/frontend)
      context: ../../frontend
      # Dockerfile: Relative to this docker-compose.yml file.
      # If this file is in infra/docker/ and Dockerfile is infra/docker/frontend/Dockerfile.frontend,
      # path is ./frontend/Dockerfile.frontend
      dockerfile: ./frontend/Dockerfile.frontend
    env_file:
      # Reference root .env file, path relative to this docker-compose.yml file
      - ../../.env  
    environment:
      # Production-specific environment variables
      - VITE_NODE_ENV=production
    ports:
      # Expose frontend port
      - "80:80"
      - "443:443"
    depends_on:
      # Ensure backend is available
      - backend
    networks:
      # Connect to shared network for inter-service communication
      - app-network
    # Automatically restart on failure
    restart: always

# ============================= NETWORKS ====================================
networks:
  # Shared network for service communication
  app-network:
    # Use bridge driver for container communication
    driver: bridge 
